# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'd:\a\1\s\WebGoat.NET.sln'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: 'd:\a\1\s\webGoat.zip'
    replaceExistingArchive: true

- task: FortifyOnDemandStatic@5
  inputs:
    FortifyProjects: 'd:\a\1\s\webGoat.zip'
    BSIToken: 'eyJ0ZW5hbnRJZCI6MTAyODcsInRlbmFudENvZGUiOiJQZXJmb3JtYW5jZV9UZWNobm9sb2dpZXNfU0FfNl9GTUFfMjMyODEwMTMwIiwicmVsZWFzZUlkIjo4NDk3MiwicGF5bG9hZFR5cGUiOiJBTkFMWVNJU19QQVlMT0FEIiwiYXNzZXNzbWVudFR5cGVJZCI6MTQsInRlY2hub2xvZ3lUeXBlIjoiLk5FVCIsInRlY2hub2xvZ3lUeXBlSWQiOjEsInRlY2hub2xvZ3lWZXJzaW9uIjoiNC43IiwidGVjaG5vbG9neVZlcnNpb25JZCI6MTYsImF1ZGl0UHJlZmVyZW5jZSI6IkF1dG9tYXRlZCIsImF1ZGl0UHJlZmVyZW5jZUlkIjoyLCJpbmNsdWRlVGhpcmRQYXJ0eSI6ZmFsc2UsImluY2x1ZGVPcGVuU291cmNlQW5hbHlzaXMiOmZhbHNlLCJwb3J0YWxVcmkiOiJodHRwczovL3RyaWFsLmZvcnRpZnkuY29tLyIsImFwaVVyaSI6Imh0dHBzOi8vYXBpLnRyaWFsLmZvcnRpZnkuY29tIiwic2NhblByZWZlcmVuY2UiOiJTdGFuZGFyZCIsInNjYW5QcmVmZXJlbmNlSWQiOjF9'
    APIAuthenticationType: '1'
    APIKey: '65a8e7d9-05ac-410d-bef0-f176eb7924b9'
    APISecret: 'VnEwXTB5KFZaUW9CUnlNRjZ5VnlybnEwaVZJKEg10'
    EntitlementPreference: '0'
    InProgressScanActionType: '0'
    RemediationScanPreference: '0'
    PurchaseEntitlements: false
    PolicyFailAction: '1'

    

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

